// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Messager is an autogenerated mock type for the Messager type
type Messager struct {
	mock.Mock
}

// Message provides a mock function with given fields:
func (_m *Messager) Message() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
